### ISSUE TITLE
[BUG] Arclight 实体死亡事件报错

### ISSUE THREAD

**Issue by Yurinann** [Rothes/Prism-Bukkit#2]
**Describe the bug**
在 Arclight 1.16 (https://github.com/IzzelAliz/Arclight) 环境下 Prism 报错

**To Reproduce**

地狱实体死亡

**Expected behavior**

**Screenshots**

报错信息:
https://paste.loliidc.cn/?7d4d4a2af6e58f4e#Ak5YiLyxMQExAMve8u5JdPrVafwFkWvunzg4rx9PCTem

**Server (please complete the following information):**
  - Prism Version: v2.1.8-CN-210822-18
  - Server Type: Arclight
  - Server Version: 1.16.5

**Additional context**

**Comment by Rothes** [comment]
这看起来是服务端的问题，它们没有正确处理 field。
```
Caused by: java.lang.IllegalAccessError: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftPiglin tried to access private field net.minecraft.entity.monster.piglin.PiglinEntity.field_234406_bA_ (org.bukkit.craftbukkit.v1_16_R3.entity.CraftPiglin and net.minecraft.entity.monster.piglin.PiglinEntity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @7d528cf7)
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPiglin.getInventory(CraftPiglin.java:77) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-921b317] {re:classloading,pl:arclight_implementer:entitytype,pl:arclight_implementer:A}
        at me.botsko.prism.listeners.PrismEntityEvents.onEntityDeath(PrismEntityEvents.java:137) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        ... 35 more
```
