### ISSUE TITLE
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by tiltysola** [Rothes/Prism-Bukkit#5]
Stack here:
```
[08:40:45] [Server thread/ERROR]: Could not load 'plugins/prism-2.1.8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:414) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]  
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]     
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        ... 6 more
```

API Version:
```
This server is running CraftBukkit version 3355-Spigot-dbf4938-3c2af1b (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)
```

Plugin Version:
```
Prism 2.1.8-CN-211023-23.jar
```

**Comment by tiltysola** [comment]
我的问题，MCBBS没登陆下载的是错误的JAR文件
